openapi: 3.0.3
info:
  title: Agent Workflow Manager API
  description: API for orchestrating agent behaviors, self-regulation, and context management
  version: 1.0.0
  contact:
    name: Spec-Kit Enhancement Initiative
    url: https://github.com/github/spec-kit

servers:
  - url: /api/v1
    description: Agent workflow manager API

paths:
  /agent/context:
    post:
      summary: Manage agent context windows
      description: Provides hierarchical context management and optimization for AI agents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContextManagementRequest'
      responses:
        '200':
          description: Context management completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContextManagementResponse'
        '400':
          description: Invalid request or missing context data
        '500':
          description: Context management failed

  /agent/prompt:
    post:
      summary: Optimize agent prompts
      description: Provides auto-prompt enhancement and optimization for AI agents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromptOptimizationRequest'
      responses:
        '200':
          description: Prompt optimization completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromptOptimizationResponse'

  /agent/validation:
    post:
      summary: Validate agent workflows
      description: Provides self-validation and correction capabilities for AI agents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentValidationRequest'
      responses:
        '200':
          description: Validation completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentValidationResponse'

components:
  schemas:
    ContextManagementRequest:
      type: object
      required:
        - project_context
        - agent_platform
      properties:
        project_context:
          type: object
          description: Current project context and state
        agent_platform:
          type: string
          enum: [claude, copilot, gemini, cursor, qwen, opencode, windsurf, kilo, auggie, roo]
          description: Target AI coding platform
        context_size:
          type: integer
          description: Available context window size
          default: 4000
        hierarchical_sections:
          type: boolean
          description: Whether to use hierarchical section management
          default: true
        optimization_level:
          type: string
          enum: [minimal, balanced, aggressive]
          description: Context optimization strategy
          default: balanced

    ContextManagementResponse:
      type: object
      properties:
        optimized_context:
          type: object
          properties:
            hierarchical_sections:
              type: array
              items:
                type: string
            prioritized_content:
              type: array
              items:
                type: string
            condensed_sections:
              type: array
              items:
                type: string
        context_metrics:
          type: object
          properties:
            original_size:
              type: integer
            optimized_size:
              type: integer
            compression_ratio:
              type: number
        recommendations:
          type: array
          items:
            type: string
          description: Recommendations for context management

    PromptOptimizationRequest:
      type: object
      required:
        - original_prompt
        - task_type
      properties:
        original_prompt:
          type: string
          description: Original agent prompt to optimize
        task_type:
          type: string
          enum: [analysis, implementation, testing, documentation, validation]
          description: Type of task being performed
        platform_specific:
          type: boolean
          description: Whether to optimize for specific platform
          default: true
        include_examples:
          type: boolean
          description: Whether to include examples
          default: true
        optimization_strategy:
          type: string
          enum: [clarity, efficiency, completeness]
          description: Optimization focus
          default: efficiency

    PromptOptimizationResponse:
      type: object
      properties:
        optimized_prompt:
          type: string
          description: Enhanced and optimized prompt
        optimization_details:
          type: object
          properties:
            clarity_improvements:
              type: array
              items:
                type: string
            efficiency_improvements:
              type: array
              items:
                type: string
            completeness_additions:
              type: array
              items:
                type: string
        platform_specific_enhancements:
          type: object
          description: Platform-specific prompt optimizations
        estimated_effectiveness:
          type: number
          minimum: 0
          maximum: 1
          description: Estimated improvement in agent performance

    AgentValidationRequest:
      type: object
      required:
        - agent_output
        - validation_criteria
      properties:
        agent_output:
          type: object
          description: Agent's output to validate
        validation_criteria:
          type: array
          items:
            type: string
          enum: [completeness, correctness, consistency, performance, compliance]
          description: Criteria to validate against
        strict_mode:
          type: boolean
          description: Whether to fail on first violation
          default: false
        platform_constraints:
          type: object
          description: Platform-specific constraints

    AgentValidationResponse:
      type: object
      properties:
        is_valid:
          type: boolean
          description: Overall validation result
        validation_results:
          type: array
          items:
            type: object
            properties:
              criterion:
                type: string
              status:
                type: string
                enum: [pass, fail, warning]
              message:
                type: string
              severity:
                type: string
                enum: [low, medium, high]
        corrections:
          type: array
          items:
            type: string
          description: Suggested corrections for validation failures
        performance_metrics:
          type: object
          properties:
            response_time:
              type: number
            accuracy_score:
              type: number
            completeness_score:
              type: number

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details