openapi: 3.0.3
info:
  title: Governance and Synchronization API
  description: API for managing artifacts, enforcing conventions, and maintaining cross-platform consistency
  version: 1.0.0
  contact:
    name: Spec-Kit Enhancement Initiative
    url: https://github.com/github/spec-kit

servers:
  - url: /api/v1
    description: Governance and synchronization API

paths:
  /governance/artifact:
    post:
      summary: Create and manage artifacts
      description: Creates new artifacts with proper metadata and relationship tracking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArtifactCreationRequest'
      responses:
        '201':
          description: Artifact created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArtifactCreationResponse'
        '400':
          description: Invalid artifact data or naming violation
        '409':
          description: Artifact already exists

  /governance/synchronize:
    post:
      summary: Synchronize artifacts across platforms
      description: Ensures consistency across platform-specific files and artifacts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SynchronizationRequest'
      responses:
        '200':
          description: Synchronization completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SynchronizationResponse'

  /governance/validate:
    post:
      summary: Validate governance compliance
      description: Validates artifacts against constitutional principles and governance rules
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidationRequest'
      responses:
        '200':
          description: Validation completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'

components:
  schemas:
    ArtifactCreationRequest:
      type: object
      required:
        - artifact_type
        - artifact_name
        - content
      properties:
        artifact_type:
          type: string
          enum: [spec, plan, research, data_model, contract, task]
          description: Type of artifact being created
        artifact_name:
          type: string
          description: Name of the artifact
        content:
          type: string
          description: Content of the artifact
        parent_artifact:
          type: string
          description: Parent artifact ID for hierarchical relationships
        platform_specific:
          type: boolean
          description: Whether this is platform-specific
          default: false
        metadata:
          type: object
          description: Additional metadata for the artifact

    ArtifactCreationResponse:
      type: object
      properties:
        artifact_id:
          type: string
          description: Unique identifier for the artifact
        relationship_id:
          type: string
          description: Hierarchical relationship identifier
        file_path:
          type: string
          description: Path where artifact was created
        validation_results:
          type: array
          items:
            type: string
          description: Validation messages

    SynchronizationRequest:
      type: object
      required:
        - source_artifact
        - target_platforms
      properties:
        source_artifact:
          type: string
          description: ID of the artifact to synchronize
        target_platforms:
          type: array
          items:
            type: string
          enum: [claude, copilot, gemini, cursor, qwen, opencode, windsurf, kilo, auggie, roo]
          description: Platforms to synchronize with
        sync_strategy:
          type: string
          enum: [full, incremental, selective]
          description: Synchronization strategy
          default: incremental

    SynchronizationResponse:
      type: object
      properties:
        synchronized_platforms:
          type: array
          items:
            type: string
          description: Platforms successfully synchronized
        failed_platforms:
          type: array
          items:
            type: string
          description: Platforms that failed synchronization
        sync_details:
          type: object
          description: Detailed synchronization results

    ValidationRequest:
      type: object
      required:
        - artifact_id
        - validation_rules
      properties:
        artifact_id:
          type: string
          description: ID of artifact to validate
        validation_rules:
          type: array
          items:
            type: string
          enum: [naming, structure, content, relationships, platform_compatibility]
          description: Rules to validate against
        strict_mode:
          type: boolean
          description: Whether to fail on first violation
          default: false

    ValidationResponse:
      type: object
      properties:
        is_valid:
          type: boolean
          description: Overall validation result
        violations:
          type: array
          items:
            type: object
            properties:
              rule:
                type: string
                description: Violated rule
              message:
                type: string
                description: Description of violation
              severity:
                type: string
                enum: [error, warning, info]
          description: List of validation violations
        recommendations:
          type: array
          items:
            type: string
          description: Recommendations for fixing violations

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details